version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PopcornPicksDB
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/movies.sql:/docker-entrypoint-initdb.d/movies.sql

  flask-app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  db_data:
