name: Black Formatting

on: [push]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black==23.7.0

      - name: Format code with Black
        run: |
          black .

      - name: Check for changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatically format code with Black"
          git pull --rebase origin refs/heads/v7.0
          git push origin refs/heads/v7.0:refs/heads/v7.0
